// <auto-generated />
using System;
using Infraestructura.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Datos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.models.adicción", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<double>("adicciónSalary")
                        .HasColumnType("double");

                    b.Property<string>("motivo")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("adicción");
                });

            modelBuilder.Entity("Core.models.user", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("core.models.employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataIn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdAdiccion")
                        .HasColumnType("int");

                    b.Property<int>("Idjob")
                        .HasColumnType("int");

                    b.Property<string>("ImagesUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("birdDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("createAt")
                        .HasColumnType("int");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("netSalary")
                        .HasColumnType("double");

                    b.Property<double>("salaryFinal")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdAdiccion");

                    b.HasIndex("Idjob");

                    b.HasIndex("createAt");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("core.models.job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nameJob")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("job");
                });

            modelBuilder.Entity("core.models.employees", b =>
                {
                    b.HasOne("Core.models.adicción", "adicción")
                        .WithMany()
                        .HasForeignKey("IdAdiccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("core.models.job", "job")
                        .WithMany()
                        .HasForeignKey("Idjob")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.models.user", "user")
                        .WithMany()
                        .HasForeignKey("createAt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("adicción");

                    b.Navigation("job");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
